### ISSUE TITLE
Wrong json key in POST /v1/accounts/{account_id}/documents/upload

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/bkdocs#2]
Endpoint: POST /v1/accounts/{account_id}/documents/upload

Issue:
The endpoint accepts an array of models.DocumentUpload, and this `document_upload` needs to be removed from the doc.

Reference:
https://github.com/alpacahq/bkdocs/blob/19f7734478bd1e2121e811140ad54290b7318b82/content/api-references/accounts/accounts.md#L540

**Comment by umitanuki** [comment]
cc @Neal

**Comment by excavator20** [comment]
Fixed: ` | `document_upload` | models.DocumentUpload | {{<hint danger>}}Required{{</hint>}} | `

**Comment by Neal** [comment]
@excavator20 I don't think it's still right. There is no `key` here really so the table header should be changed I guess. The request body accepts an array of `models.DocumentUpload` so the `document_upload` key you mention is misleading.
