### ISSUE TITLE
Wrong type in extended_hours

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/bkdocs#3]
https://github.com/alpacahq/bkdocs/blob/19f7734478bd1e2121e811140ad54290b7318b82/content/api-references/trading/orders.md#L86

This should be boolean

**Comment by umitanuki** [comment]
cc @Neal

**Comment by Neal** [comment]
Also `legs` right after it should be an array.

**Comment by mahmoudksherif** [comment]
fixed. will close.
