### ISSUE TITLE
Going Live link 404s on broker integration docs page

### ISSUE THREAD

**Issue by jwage** [alpacahq/bkdocs#5]
On this page https://alpaca.markets/docs/broker/integration/ there is a link for Going Live which points to https://alpaca.markets/docs/integration/#going-live and it currently 404s

In this file https://github.com/alpacahq/bkdocs/blob/master/content/integration/_index.md

```
To go live, we will onboard you for the business integration. For more details
of this step, please refer to [Going Live](/docs/integration/#going-live)
```

**Comment by mahmoudksherif** [comment]
thanks for catching that! fixed. will close
